security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        api_key_user_provider:
            id: AppBundle\Security\ApiKeyUserProvider

    firewalls:
        login:
          pattern: ^/login
          security: false
        main:
          pattern: ^/
          stateless: true
          simple_preauth:
            authenticator: AppBundle\Security\ApiKeyAuthenticator
            provider: api_key_user_provider

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }