task_list:
  path: task
  defaults: { _controller: AppBundle:Task:list }
  methods: [GET]

task_create:
  path: task
  defaults: { _controller: AppBundle:Task:create }
  methods: [POST]

task_delete:
  path: task/{id}
  defaults: { _controller: AppBundle:Task:delete }
  methods: [DELETE]
  requirements:
    id: "\\d+"
